{% set name = "fsleyes-plugin-mrs" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 69b59bfd1998a92b48893585a2174a67c81e7169c7ed38a6793f820ad9da01b3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fsleyes >=1.0.10,<2.0
    - fsleyes-widgets >=0.16.0,<1.0
    - file-tree >=1.6.1,<2.0
    - seaborn >=0.12.0,<1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fsleyes_plugin_mrs

about:
  home: https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An FSLeyes extension for viewing MRS(I) data formatted as NIfTI-MRS.
  # The remaining entries in this section are optional, but recommended.
  description: |
    This plugin adds an additional MRS specific view panel to FSLeyes which displays spectra in the frequency domain. Higher dimensions of data stored in NIfTI-MRS format may be explored.
  dev_url: https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs

extra:
  recipe-maintainers:
    - vkarlaftis
    - wtclarke
