{% set name = "fsleyes-plugin-mrs" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a216c242704c83c14137a1745a11763412a23d226528139fa72a36423bd786ad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fsleyes

test:
  requires:
    - python {{ python_min }}
  imports:
    - fsleyes_plugin_mrs

about:
  home: https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An FSLeyes extension for viewing MRS(I) data formatted as NIfTI-MRS.
  # The remaining entries in this section are optional, but recommended.
  description: |
    This plugin adds an additional MRS specific view panel to FSLeyes which displays spectra in the frequency domain. Higher dimensions of data stored in NIfTI-MRS format may be explored.
  dev_url: https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs

extra:
  recipe-maintainers:
    - vkarlaftis
    - wtclarke
