{% set name = "fsleyes-plugin-mrs" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4f93a5752e9f3eec2b109e8218146b8ec946593cd56765ce47ddde35a6252c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fsleyes

test:
  imports:
    - fsleyes_plugin_mrs

about:
  home: https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An FSLeyes extension for viewing MRS(I) data formatted as NIfTI-MRS.
  # The remaining entries in this section are optional, but recommended.
  description: |
    This plugin adds an additional MRS specific view panel to FSLeyes which displays spectra in the frequency domain. Higher dimensions of data stored in NIfTI-MRS format may be explored.
  dev_url: https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs

extra:
  recipe-maintainers:
    - wtclarke
